// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains runtime counts shown by the Quit confirmation dialog.
 */
export type QuitSummaryDto = { sessionCount: number, projectCount: number, runningProcessCount: number, unsavedFileCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one pending Quit request and its immutable snapshot.
 */
export type QuitRequestDto = { requestId: number, summary: QuitSummaryDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries an opaque session identifier to frontend navigation.
 */
export type SessionNavigationDto = { sessionId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the native main-window operation that failed.
 */
export type WindowOperation = "show" | "hide" | "unminimize" | "focus" | "minimize" | "read_maximized" | "maximize" | "unmaximize";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the native tray operation that failed.
 */
export type TrayOperation = "create_icon" | "build_menu" | "replace_menu";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the lifecycle event that could not be delivered.
 */
export type LifecycleEvent = "quit_requested" | "navigate_session";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes lifecycle failures without exposing native or runtime details.
 */
export type AppLifecycleError = { "code": "invalid_window" } | { "code": "unauthorized_window" } | { "code": "main_window_unavailable" } | { "code": "window_operation_failed", operation: WindowOperation, } | { "code": "tray_operation_failed", operation: TrayOperation, } | { "code": "event_delivery_failed", event: LifecycleEvent, } | { "code": "runtime_snapshot_failed" } | { "code": "runtime_shutdown_failed" } | { "code": "invalid_request_id" } | { "code": "stale_quit_request" } | { "code": "quit_already_in_progress" } | { "code": "state_lock_poisoned" };
