// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarWeekdayDto = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventRecurrenceEndDto = { "kind": "never" } | { "kind": "on_date", date: string, } | { "kind": "after_count", count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventRecurrenceDto = { "kind": "none" } | { "kind": "daily", end: EventRecurrenceEndDto, } | { "kind": "weekly", weekdays: Array<CalendarWeekdayDto>, end: EventRecurrenceEndDto, } | { "kind": "monthly", end: EventRecurrenceEndDto, } | { "kind": "yearly", end: EventRecurrenceEndDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventTimeInputDto = { "kind": "timed", startLocal: string, endLocal: string, timeZoneId: string, } | { "kind": "all_day", startDate: string, endDateExclusive: string, timeZoneId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventTimeDto = { "kind": "timed", startLocal: string, endLocal: string, timeZoneId: string, startAtMs: number, endAtMs: number, } | { "kind": "all_day", startDate: string, endDateExclusive: string, timeZoneId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventInputDto = { title: string, description: string, projectId: string | null, time: EventTimeInputDto, recurrence: EventRecurrenceDto, reminderMinutesBefore: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventReminderDto = { id: string, minutesBefore: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEventDto = { id: string, title: string, description: string, projectId: string | null, time: EventTimeDto, recurrence: EventRecurrenceDto, reminders: Array<EventReminderDto>, revision: string, createdAtMs: number, updatedAtMs: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarRangeInputDto = { startDate: string, endDateExclusive: string, viewerTimeZoneId: string, projectId: string | null, onlyWithReminders: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarOccurrenceDto = { occurrenceId: string, eventId: string, title: string, projectId: string | null, time: EventTimeDto, recurrence: EventRecurrenceDto, reminders: Array<EventReminderDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarOccurrenceListDto = { revision: string, items: Array<CalendarOccurrenceDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventRevisionInputDto = { eventId: string, expectedRevision: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCalendarEventInputDto = { eventId: string, expectedRevision: string, event: EventInputDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteCalendarEventImpactDto = { requestId: number, eventId: string, title: string, isRecurring: boolean, reminderCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfirmDeleteCalendarEventInputDto = { requestId: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletedCalendarEventDto = { eventId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarChangeKindDto = "created" | "updated" | "deleted" | "backup_imported" | "reset";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarChangedEventDto = { sequence: string, kind: CalendarChangeKindDto, eventId: string | null, revision: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarError = { "kind": "unauthorized_caller" } | { "kind": "invalid_event_id" } | { "kind": "invalid_revision" } | { "kind": "invalid_title" } | { "kind": "description_too_long" } | { "kind": "invalid_project_id" } | { "kind": "project_not_found" } | { "kind": "project_changed" } | { "kind": "invalid_date" } | { "kind": "invalid_local_date_time" } | { "kind": "invalid_time_zone" } | { "kind": "nonexistent_local_time" } | { "kind": "invalid_time_range" } | { "kind": "date_out_of_range" } | { "kind": "invalid_recurrence" } | { "kind": "invalid_recurrence_end" } | { "kind": "too_many_reminders" } | { "kind": "duplicate_reminder" } | { "kind": "invalid_reminder_offset" } | { "kind": "invalid_range" } | { "kind": "occurrence_limit_exceeded" } | { "kind": "event_not_found" } | { "kind": "revision_conflict", currentRevision: string, } | { "kind": "delete_confirmation_missing" } | { "kind": "delete_confirmation_expired" } | { "kind": "delete_impact_changed" } | { "kind": "corrupt_stored_data" } | { "kind": "storage_unavailable" };
