// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the backend-resolved application data location.
 */
export type DataLocationDto = { directory: string, databaseFileName: string, logsDirectoryName: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts backup records without exposing their content.
 */
export type BackupContentCountsDto = { projects: number, customCliProfiles: number, secretReferences: number, keyboardShortcutOverrides: number, notes: number | null, events: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports picker cancellation or a completed export.
 */
export type BackupExportOutcomeDto = { "kind": "cancelled" } | { "kind": "exported", fileName: string, schemaVersion: number, counts: BackupContentCountsDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarizes identity-level changes prepared by an import.
 */
export type BackupMergeCountsDto = { inserts: number, updates: number, unchanged: number, removals: number, projectPathMatches: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries an immutable import preview tied to one pending request.
 */
export type BackupImportPreviewDto = { requestId: number, schemaVersion: number, createdAtMs: bigint, sourceAppVersion: string, counts: BackupContentCountsDto, merge: BackupMergeCountsDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports picker cancellation or an import ready for confirmation.
 */
export type PrepareBackupImportOutcomeDto = { "kind": "cancelled" } | { "kind": "ready", preview: BackupImportPreviewDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports the committed import and durable cleanup backlog.
 */
export type BackupImportResultDto = { schemaVersion: number, applied: BackupMergeCountsDto, credentialCleanupPending: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes durable and runtime state affected by a confirmed reset.
 */
export type ResetImpactDto = { requestId: number, projects: number, customCliProfiles: number, keyboardShortcutOverrides: number, settingsDifferFromDefault: boolean, notes: number, events: number, sessions: number, runningProcesses: number, unsavedDocuments: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports the exact committed Phase 1 reset counts.
 */
export type ResetResultDto = { projectsRemoved: number, customCliProfilesRemoved: number, keyboardShortcutOverridesRemoved: number, settingsReset: boolean, notesRemoved: number, eventsRemoved: number, sessionsStopped: number, credentialCleanupPending: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the committed aggregate data change.
 */
export type DataChangeKindDto = "backup_imported" | "app_reset";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invalidates frontend projections after all owners publish.
 */
export type DataChangedEventDto = { kind: DataChangeKindDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the owner that rejected one backup section.
 */
export type BackupDomainDto = "projects" | "settings" | "cli_profiles" | "keyboard_shortcuts" | "notes" | "events";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposes stable Data Management failures without paths or user content.
 */
export type DataManagementError = { "code": "unauthorized_window" } | { "code": "operation_in_progress" } | { "code": "no_pending_operation" } | { "code": "stale_request" } | { "code": "invalid_reset_confirmation" } | { "code": "data_location_unavailable" } | { "code": "open_location_failed" } | { "code": "clipboard_write_failed" } | { "code": "file_read_failed" } | { "code": "file_write_failed" } | { "code": "backup_too_large" } | { "code": "invalid_backup" } | { "code": "unsupported_backup_version", found: number, supported: number, } | { "code": "serialize_failed" } | { "code": "snapshot_failed" } | { "code": "domain_validation_failed", domain: BackupDomainDto, } | { "code": "import_preview_changed", preview: BackupImportPreviewDto, } | { "code": "runtime_unavailable" } | { "code": "runtime_cleanup_failed" } | { "code": "persistence_failed" };
