// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a layout-independent keyboard chord.
 */
export type ShortcutChordDto = { primary: boolean, alt: boolean, shift: boolean, keyCode: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Groups catalog actions for presentation.
 */
export type ShortcutCategoryDto = "global" | "navigation" | "tabs" | "panes" | "files";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the focus boundary of a shortcut.
 */
export type ShortcutScopeDto = "application" | "global";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one action with its effective chord and complete conflict group.
 */
export type KeyboardShortcutActionDto = { actionId: string, label: string, category: ShortcutCategoryDto, scope: ShortcutScopeDto, defaultChord: ShortcutChordDto, currentChord: ShortcutChordDto, isCustom: boolean, conflictsWith: Array<string>, isDispatchable: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the committed catalog in declaration order.
 */
export type KeyboardShortcutsDto = { actions: Array<KeyboardShortcutActionDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the typed shortcut assignment input.
 */
export type SetKeyboardShortcutInputDto = { actionId: string, chord: ShortcutChordDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposes stable errors without database details.
 */
export type KeyboardShortcutsError = { "code": "unauthorized_window" } | { "code": "action_not_found", action_id: string, } | { "code": "invalid_key_code", key_code: string, } | { "code": "modifier_required" } | { "code": "reserved_shortcut" } | { "code": "corrupt_stored_shortcut", action_id: string, } | { "code": "persistence_failed" } | { "code": "unavailable" };
