// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteStatusDto = "active" | "archived" | "trash";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotePreviousStatusDto = "active" | "archived";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotePinnedFilterDto = "any" | "only" | "exclude";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteProjectFilterDto = { "kind": "all" } | { "kind": "unlinked" } | { "kind": "project", projectId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListNotesInputDto = { status: NoteStatusDto, query: string | null, projectFilter: NoteProjectFilterDto, pinnedFilter: NotePinnedFilterDto, offset: number, limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteTextRangeDto = { startScalar: number, endScalar: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteSummaryDto = { id: string, title: string | null, snippet: string, projectId: string | null, isPinned: boolean, status: NoteStatusDto, createdAtMs: number, updatedAtMs: number, archivedAtMs: number | null, trashedAtMs: number | null, revision: string, titleHighlights: Array<NoteTextRangeDto>, snippetHighlights: Array<NoteTextRangeDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteDto = { id: string, title: string | null, contentMarkdown: string, projectId: string | null, isPinned: boolean, status: NoteStatusDto, trashedFrom: NotePreviousStatusDto | null, createdAtMs: number, updatedAtMs: number, archivedAtMs: number | null, trashedAtMs: number | null, revision: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteCountsDto = { active: number, archived: number, trash: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteListPageDto = { items: Array<NoteSummaryDto>, offset: number, totalMatches: number, hasMore: boolean, counts: NoteCountsDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNoteInputDto = { title: string | null, contentMarkdown: string, projectId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutosaveNoteInputDto = { noteId: string, expectedRevision: string, title: string | null, contentMarkdown: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetNotePinnedInputDto = { noteId: string, expectedRevision: string, pinned: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetNoteProjectInputDto = { noteId: string, expectedRevision: string, projectId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteRevisionInputDto = { noteId: string, expectedRevision: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeletedNoteDto = { noteId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrashNoteLabelDto = { noteId: string, displayTitle: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmptyNotesTrashImpactDto = { requestId: number, noteCount: number, notes: Array<TrashNoteLabelDto>, hasMore: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmptyNotesTrashResultDto = { deletedCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteChangeKindDto = "created" | "autosaved" | "pinned_changed" | "project_changed" | "archived" | "restored" | "trashed" | "permanently_deleted" | "trash_emptied" | "backup_imported" | "reset";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteChangedEventDto = { sequence: string, kind: NoteChangeKindDto, noteId: string | null, revision: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotesError = { "code": "unauthorized_window" } | { "code": "invalid_note_id" } | { "code": "invalid_revision" } | { "code": "invalid_title" } | { "code": "empty_initial_content" } | { "code": "content_too_large" } | { "code": "invalid_search" } | { "code": "invalid_pagination" } | { "code": "invalid_filter" } | { "code": "invalid_project_id" } | { "code": "project_not_found" } | { "code": "note_not_found" } | { "code": "note_not_editable", status: NoteStatusDto, } | { "code": "invalid_transition", status: NoteStatusDto, } | { "code": "revision_conflict", current: NoteDto, } | { "code": "revision_exhausted" } | { "code": "trash_empty" } | { "code": "no_pending_trash_operation" } | { "code": "stale_trash_request" } | { "code": "trash_changed", impact: EmptyNotesTrashImpactDto, } | { "code": "clock_failed" } | { "code": "persistence_failed" };
