// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuickNoteGlobalShortcutStateDto = "active" | "disabled_by_conflict" | "unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShortcutChordDto } from "./keyboard-shortcuts";

export type QuickNoteGlobalShortcutStatusDto = { sequence: string, actionId: string, chord: ShortcutChordDto, state: QuickNoteGlobalShortcutStateDto, conflictsWith: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuickNoteWindowOperation = "create" | "show" | "unminimize" | "focus" | "close" | "start_dragging";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuickNoteWindowError = { "code": "unauthorized_window" } | { "code": "app_shutting_down" } | { "code": "stale_window" } | { "code": "window_operation_failed", operation: QuickNoteWindowOperation, } | { "code": "unavailable" };
