// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderDeliveryStatusDto = "active" | "missed" | "snoozed" | "dismissed" | "suppressed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderDeliveryDto = { id: string, eventId: string, occurrenceId: string, projectId: string | null, title: string, startsAtMs: string, originalDueAtMs: string, timeZoneId: string, minutesBefore: number, status: ReminderDeliveryStatusDto, snoozedUntilMs: string | null, version: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderCursorDto = { originalDueAtMs: string, id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissedReminderPageDto = { sequence: string, missedCount: number, items: Array<ReminderDeliveryDto>, nextCursor: ReminderCursorDto | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventReminderDeliveriesDto = { sequence: string, eventId: string, occurrenceId: string, items: Array<ReminderDeliveryDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderTargetDto = { eventId: string, occurrenceId: string, projectId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderActionResultDto = { sequence: string, missedCount: number, delivery: ReminderDeliveryDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VisibleCalendarEventInputDto = { "kind": "show", viewToken: string, eventId: string, occurrenceId: string | null, } | { "kind": "hide", viewToken: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderChangedDto = { sequence: string, missedCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReminderError = { "code": "unauthorized_window" } | { "code": "invalid_delivery_id" } | { "code": "invalid_event_id" } | { "code": "invalid_occurrence_id" } | { "code": "invalid_view_token" } | { "code": "invalid_version" } | { "code": "invalid_cursor" } | { "code": "invalid_limit", min: number, max: number, } | { "code": "invalid_snooze_minutes" } | { "code": "delivery_not_found" } | { "code": "delivery_changed" } | { "code": "action_not_allowed" } | { "code": "target_unavailable" } | { "code": "clock_out_of_range" } | { "code": "scheduler_catching_up" } | { "code": "dependency_unavailable" } | { "code": "corrupt_stored_delivery", field: string, } | { "code": "persistence_failed" } | { "code": "unavailable" };
