// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accepts one unified-search request from the frontend.
 */
export type UnifiedSearchInputDto = { query: string, contextProjectId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one half-open Unicode-scalar range in display text.
 */
export type SearchTextRangeDto = { startScalar: number, endScalar: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the domain represented by a result or group.
 */
export type SearchResultKindDto = "project" | "session" | "command";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the current shortcut shown beside a command result.
 */
export type SearchShortcutDto = { primary: boolean, alt: boolean, shift: boolean, keyCode: string, isConflicted: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the owner action for one Phase 1 result.
 */
export type SearchTargetDto = { "kind": "project", projectId: string, } | { "kind": "session", projectId: string, sessionId: string, } | { "kind": "command", actionId: string, projectId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one ranked and display-ready search result.
 */
export type SearchResultDto = { key: string, kind: SearchResultKindDto, title: string, context: string | null, titleHighlights: Array<SearchTextRangeDto>, contextHighlights: Array<SearchTextRangeDto>, target: SearchTargetDto, shortcut: SearchShortcutDto | null, supportsOpenInSplit: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Groups ranked results from one active source.
 */
export type SearchGroupDto = { kind: SearchResultKindDto, label: string, results: Array<SearchResultDto>, hasMore: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one active Phase 1 source.
 */
export type SearchSourceDto = "projects" | "sessions" | "commands";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a sanitized source failure.
 */
export type SearchSourceFailureReasonDto = "timeout" | "unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports an unavailable source without exposing owner details.
 */
export type SearchSourceFailureDto = { source: SearchSourceDto, reason: SearchSourceFailureReasonDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the normalized query and all successful result groups.
 */
export type UnifiedSearchResponseDto = { query: string, groups: Array<SearchGroupDto>, resultCount: number, sourceFailures: Array<SearchSourceFailureDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposes stable top-level failures at the search command boundary.
 */
export type UnifiedSearchError = { "code": "unauthorized_window" } | { "code": "invalid_query" } | { "code": "invalid_context_project_id" } | { "code": "unavailable" };
