// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the only interface language supported in Phase 1.
 */
export type InterfaceLanguageDto = "english";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects a fixed or operating-system-driven interface theme mode.
 */
export type ThemeModeDto = "light" | "dark" | "system";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a built-in color preset or a customized palette.
 */
export type ThemePresetDto = "cream" | "ink" | "paper" | "custom";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the four interface colors for one effective theme mode.
 */
export type InterfaceColorsDto = { accent: string, canvas: string, sidebar: string, text: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains both light and dark interface color sets.
 */
export type InterfaceThemeColorsDto = { light: InterfaceColorsDto, dark: InterfaceColorsDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the terminal foreground, background, and fixed ANSI palette.
 */
export type TerminalPaletteDto = { background: string, foreground: string, ansiColors: [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string], };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the immutable General behavior owned by the application lifecycle.
 */
export type GeneralSettingsDto = { interfaceLanguage: InterfaceLanguageDto, closeToTray: boolean, showTrayIcon: boolean, askBeforeQuitting: boolean, openAtHomeOnLaunch: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns every persisted Appearance setting.
 */
export type AppearanceSettingsDto = { themeMode: ThemeModeDto, themePreset: ThemePresetDto, interfaceColors: InterfaceThemeColorsDto, terminalPalette: TerminalPaletteDto, interfaceFontSizePx: number, terminalFontSizePx: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the persisted sidebar layout state.
 */
export type SidebarSettingsDto = { widthPx: number, collapsed: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the complete Phase 1 application settings contract.
 */
export type AppSettingsDto = { revision: string, general: GeneralSettingsDto, appearance: AppearanceSettingsDto, sidebar: SidebarSettingsDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes an optional partial Appearance update.
 */
export type AppearanceSettingsPatchDto = { themeMode?: ThemeModeDto, themePreset?: ThemePresetDto, interfaceColors?: InterfaceThemeColorsDto, terminalPalette?: TerminalPaletteDto, interfaceFontSizePx?: number, terminalFontSizePx?: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes an optional partial sidebar update.
 */
export type SidebarSettingsPatchDto = { widthPx?: number, collapsed?: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one atomic partial settings update.
 */
export type UpdateSettingsDto = { appearance?: AppearanceSettingsPatchDto, sidebar?: SidebarSettingsPatchDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes stable Settings failures without exposing SQLite details.
 */
export type SettingsError = { "code": "unauthorized_window" } | { "code": "empty_patch" } | { "code": "invalid_color", field: string, } | { "code": "contrast_too_low", foreground: string, background: string, } | { "code": "value_out_of_range", field: string, min: number, max: number, } | { "code": "invalid_preset_combination" } | { "code": "corrupt_stored_settings", field: string, } | { "code": "persistence_failed" } | { "code": "unavailable" };
