// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes the immutable built-in profiles from user-owned profiles.
 */
export type CliProfileKindDto = "builtIn" | "custom";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports the last known launch availability of one profile.
 */
export type CliProfileAvailabilityStatusDto = "unchecked" | "available" | "commandNotFound" | "shellNotFound";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports one availability status together with its completion time.
 */
export type CliProfileAvailabilityDto = { status: CliProfileAvailabilityStatusDto, checkedAtUnixMs: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one environment entry without ever carrying a secret value.
 */
export type CliProfileEnvironmentDto = { name: string, value: string | null, isSecret: boolean, hasStoredValue: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accepts one environment entry that may carry a plaintext secret value.
 *
 * The type intentionally derives neither `Debug`, `Clone`, nor `Serialize`
 * so a supplied secret cannot reach a log, a clone, or an outgoing payload.
 */
export type CliProfileEnvironmentInputDto = { name: string, value?: string, isSecret: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accepts one complete custom profile configuration from the frontend.
 *
 * The type intentionally derives neither `Debug`, `Clone`, nor `Serialize`
 * because its environment entries may carry plaintext secret values.
 */
export type CliProfileInputDto = { name: string, command: string, arguments: Array<string>, shellId?: string, icon: string, color: string, environment: Array<CliProfileEnvironmentInputDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one catalog shell with its current availability and default flag.
 */
export type CliShellDto = { id: string, displayName: string, command: string, isAvailable: boolean, isDefault: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one built-in or custom profile with its resolved presentation data.
 */
export type CliProfileDto = { id: string, name: string, kind: CliProfileKindDto, command: string | null, arguments: Array<string>, shellId: string | null, effectiveShellId: string, icon: string, color: string, environment: Array<CliProfileEnvironmentDto>, availability: CliProfileAvailabilityDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the complete profile and shell catalog snapshot.
 */
export type CliProfilesSnapshotDto = { revision: string, defaultShellId: string, effectiveDefaultShellId: string, shells: Array<CliShellDto>, profiles: Array<CliProfileDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Names the observable change that invalidated the previous snapshot.
 */
export type CliProfilesChangeKindDto = "created" | "updated" | "deleted" | "defaultShellChanged" | "availabilityChanged";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries one invalidation payload without any profile configuration.
 */
export type CliProfilesChangedDto = { revision: string, kind: CliProfilesChangeKindDto, profileId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes CLI profile failures without leaking paths, values, or accounts.
 */
export type CliProfilesError = { "code": "unauthorizedWindow" } | { "code": "profileNotFound" } | { "code": "builtInProfileReadOnly" } | { "code": "tooManyProfiles" } | { "code": "invalidName" } | { "code": "invalidCommand" } | { "code": "invalidArguments" } | { "code": "invalidShell" } | { "code": "invalidIcon" } | { "code": "invalidColor" } | { "code": "invalidEnvironmentName" } | { "code": "duplicateEnvironmentName" } | { "code": "tooManyEnvironmentVariables" } | { "code": "invalidEnvironmentValue" } | { "code": "secretValueRequired" } | { "code": "commandNotFound" } | { "code": "shellNotFound" } | { "code": "credentialStoreUnavailable" } | { "code": "secretWriteFailed" } | { "code": "secretReadFailed" } | { "code": "secretNotFound" } | { "code": "commandResolutionFailed" } | { "code": "persistenceFailed" };
