// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains a measured terminal grid size.
 */
export type PtySizeDto = { columns: number, rows: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the public process state of a terminal.
 */
export type TerminalProcessStateDto = "running" | "closing" | "exited" | "failed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a launch profile that cannot currently resolve.
 */
export type TerminalProfileUnavailableReasonDto = "commandNotFound" | "shellNotFound" | "credentialMissing" | "credentialStoreUnavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the safe public snapshot of one terminal runtime.
 */
export type TerminalDto = { id: string, sessionId: string, tabId: string, paneId: string, profileId: string, title: string, size: PtySizeDto, state: TerminalProcessStateDto, exitCode: string | null, wasTerminated: boolean, needsAttention: boolean, outputSubscribed: boolean, latestOutputSequence: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports output replay boundaries after attaching a subscriber.
 */
export type TerminalSubscriptionDto = { terminal: TerminalDto, firstAvailableSequence: string, latestSequence: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges one fully written terminal input chunk.
 */
export type TerminalInputAckDto = { acceptedSequence: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges the latest applied terminal resize.
 */
export type TerminalResizeAckDto = { acceptedSequence: string, size: PtySizeDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies one low-frequency terminal state change.
 */
export type TerminalStateChangeKindDto = "processChanged" | "attentionChanged" | "streamDetached" | "disposed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries a safe terminal state change without terminal bytes.
 */
export type TerminalStateChangedDto = { change: TerminalStateChangeKindDto, terminal: TerminalDto, finalOutputSequence: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes stable Terminal failures without exposing launch or stream data.
 */
export type TerminalError = { "code": "unauthorizedWindow" } | { "code": "invalidRuntimeId", field: string, } | { "code": "sessionNotFound", sessionId: string, } | { "code": "tabNotFound", tabId: string, } | { "code": "paneNotFound", paneId: string, } | { "code": "paneNotLaunchable", paneId: string, } | { "code": "terminalAlreadyAttached", paneId: string, terminalId: string | null, } | { "code": "projectNotFound", projectId: string, } | { "code": "projectUnavailable", projectId: string, } | { "code": "projectLookupFailed" } | { "code": "profileNotFound", profileId: string, } | { "code": "profileUnavailable", profileId: string, reason: TerminalProfileUnavailableReasonDto, } | { "code": "profileLookupFailed" } | { "code": "invalidPtySize" } | { "code": "invalidSequence", field: string, } | { "code": "inputOutOfOrder", expectedSequence: string, receivedSequence: string, } | { "code": "inputTooLarge", maxBytes: number, } | { "code": "terminalNotFound", terminalId: string, } | { "code": "terminalNotRunning", terminalId: string, } | { "code": "outputReplayUnavailable", firstAvailableSequence: string, latestSequence: string, } | { "code": "streamAttachFailed" } | { "code": "ptyUnavailable" } | { "code": "ptyOpenFailed" } | { "code": "processSpawnFailed" } | { "code": "processIoFailed" } | { "code": "resizeFailed" } | { "code": "terminationFailed" } | { "code": "sessionAttachFailed" } | { "code": "runtimeShuttingDown" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes stable terminal clipboard and web-link failures.
 */
export type TerminalInteractionError = { "code": "unauthorizedWindow" } | { "code": "invalidRuntimeId" } | { "code": "terminalNotFound", terminalId: string, } | { "code": "terminalNotRunning", terminalId: string, } | { "code": "clipboardUnavailable" } | { "code": "unsupportedClipboardText" } | { "code": "invalidLink" } | { "code": "linkOpenFailed" } | { "code": "runtimeShuttingDown" };
