// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the three Phase 1 terminal occurrences.
 */
export type NotificationKindDto = "terminalNeedsInput" | "terminalProcessFinished" | "terminalProcessFailed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns an opaque live route without exposing terminal source identity.
 */
export type NotificationTargetDto = { "kind": "session", projectId: string, sessionId: string, tabId: string, paneId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains one sanitized event-time notification snapshot.
 */
export type NotificationDto = { id: string, kind: NotificationKindDto, title: string, context: string, target: NotificationTargetDto, statusCode: string | null, createdAtMs: string, readAtMs: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the last descending key from the preceding page.
 */
export type NotificationCursorDto = { createdAtMs: string, id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns a bounded page and the whole-center unread count.
 */
export type NotificationPageDto = { revision: string, unreadCount: number, items: Array<NotificationDto>, nextCursor: NotificationCursorDto | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports one committed mutation or unchanged snapshot.
 */
export type NotificationCenterStateDto = { revision: string, unreadCount: number, affectedCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Combines an exact live navigation target with its read-state change.
 */
export type OpenNotificationDto = { target: NotificationTargetDto, state: NotificationCenterStateDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invalidates frontend page caches after a committed change.
 */
export type NotificationCenterChangedDto = { revision: string, unreadCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exposes stable error categories without database or user content.
 */
export type NotificationError = { "code": "unauthorized_window" } | { "code": "invalid_notification_id" } | { "code": "invalid_cursor" } | { "code": "invalid_limit", min: number, max: number, } | { "code": "notification_not_found" } | { "code": "target_unavailable" } | { "code": "dependency_unavailable" } | { "code": "corrupt_stored_notification", field: string, } | { "code": "persistence_failed" } | { "code": "unavailable" };
