// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports the highest-priority aggregate state of one session.
 */
export type SessionStatusDto = "noToolYet" | "running" | "unseenOutput" | "needsAttention" | "finished" | "exitedWithError";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the public content attached to one pane.
 */
export type PaneContentDto = { "kind": "empty" } | { "kind": "toolSelection", profileId: string, title: string, } | { "kind": "terminal", terminalId: string, profileId: string, title: string, } | { "kind": "file", fileHandleId: string, title: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains the opaque identity and public content of one pane.
 */
export type PaneDto = { id: string, content: PaneContentDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies how the two children of a split are arranged.
 */
export type SplitAxisDto = "horizontal" | "vertical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a leaf pane or a full binary split node.
 */
export type PaneLayoutNodeDto = { "kind": "pane", pane: PaneDto, } | { "kind": "split", splitId: string, axis: SplitAxisDto, ratioBasisPoints: number, first: PaneLayoutNodeDto, second: PaneLayoutNodeDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains one tab and its complete pane layout.
 */
export type TabDto = { id: string, name: string, layout: PaneLayoutNodeDto, activePaneId: string, maximizedPaneId: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarizes one process-local session for grouped lists and events.
 */
export type SessionSummaryDto = { id: string, projectId: string, name: string, status: SessionStatusDto, runningProcessCount: number, tabCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains one complete immutable session snapshot.
 */
export type SessionDetailDto = { summary: SessionSummaryDto, tabs: Array<TabDto>, activeTabId: string | null, canReopenLastClosedTab: boolean, revision: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the direction in which a new pane is inserted.
 */
export type SplitDirectionDto = "right" | "down";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the exact runtime structure requested for closing.
 */
export type CloseTargetDto = { "kind": "session", sessionId: string, } | { "kind": "tab", sessionId: string, tabId: string, } | { "kind": "pane", sessionId: string, tabId: string, paneId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports current process and unsaved-file blockers for a close target.
 */
export type CloseImpactDto = { target: CloseTargetDto, requiresConfirmation: boolean, runningProcessCount: number, runningProcessLabels: Array<string>, unsavedFileCount: number, unsavedFileLabels: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the surviving session snapshot after a close mutation.
 */
export type CloseResultDto = { target: CloseTargetDto, session: SessionDetailDto | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies the observable change represented by a runtime event.
 */
export type SessionChangeKindDto = "created" | "updated" | "activityChanged" | "deleted";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries a committed runtime invalidation and its post-mutation summary.
 */
export type SessionRuntimeEventDto = { revision: string, change: SessionChangeKindDto, projectId: string, sessionId: string, summary: SessionSummaryDto | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes stable Sessions failures without exposing user content or native errors.
 */
export type SessionsError = { "code": "unauthorizedWindow" } | { "code": "projectNotFound", projectId: string, } | { "code": "projectUnavailable", projectId: string, } | { "code": "projectLookupFailed" } | { "code": "profileNotFound", profileId: string, } | { "code": "profileUnavailable", profileId: string, } | { "code": "profileLookupFailed" } | { "code": "sessionNotFound", sessionId: string, } | { "code": "tabNotFound", tabId: string, } | { "code": "paneNotFound", paneId: string, } | { "code": "splitNotFound", splitId: string, } | { "code": "invalidName" } | { "code": "invalidMove" } | { "code": "invalidSplitRatio" } | { "code": "paneLimitReached" } | { "code": "sessionNotEmpty" } | { "code": "paneNotEmpty" } | { "code": "noClosedTab", sessionId: string, } | { "code": "confirmationRequired", impact: CloseImpactDto, } | { "code": "closeInProgress", sessionId: string, } | { "code": "contentLifecycleFailed", operation: string, targetId: string, } | { "code": "runtimeShuttingDown" };
