// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests one page of visible direct children.
 */
export type ListFileChildrenRequestDto = { projectId: string, directory: string, cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a recursive visible-entry basename search.
 */
export type SearchFileTreeRequestDto = { projectId: string, query: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one registered-project entry.
 */
export type FileEntryRequestDto = { projectId: string, relativePath: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a tree entry without following links.
 */
export type FileTreeEntryKindDto = "directory" | "file" | "symbolicLink" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one lossless project-relative filesystem entry.
 */
export type FileTreeEntryDto = { name: string, relativePath: string, kind: FileTreeEntryKindDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a recoverable traversal issue.
 */
export type FileTreeWarningReasonDto = "unreadableEntry" | "invalidIgnoreRule" | "unsupportedName";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports one recoverable issue without leaking an absolute path.
 */
export type FileTreeWarningDto = { relativeDirectory: string, reason: FileTreeWarningReasonDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns a stable page of direct children.
 */
export type FileTreePageDto = { projectId: string, directory: string, entries: Array<FileTreeEntryDto>, nextCursor: string | null, warningCount: number, warningsTruncated: boolean, warnings: Array<FileTreeWarningDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains why a recursive search returned only a deterministic prefix.
 */
export type FileSearchTruncatedReasonDto = "resultLimit" | "scanLimit" | "depthLimit";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns flat matches from one fresh project scan.
 */
export type FileTreeSearchDto = { projectId: string, query: string, matches: Array<FileTreeEntryDto>, truncatedReason: FileSearchTruncatedReasonDto | null, warningCount: number, warningsTruncated: boolean, warnings: Array<FileTreeWarningDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns copyable lexical paths for one freshly validated entry.
 */
export type FileEntryPathsDto = { relativePath: string, absolutePath: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests opening one project-relative file in an empty pane.
 */
export type OpenFileInPaneRequestDto = { sessionId: string, tabId: string, paneId: string, relativePath: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one process-local file handle.
 */
export type FileHandleRequestDto = { fileHandleId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects how an external Markdown conflict is resolved in memory.
 */
export type ExternalFileResolutionDto = "keepMine" | "reloadFromDisk";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests resolving a conflict against an exact handle revision.
 */
export type ResolveExternalFileChangeRequestDto = { fileHandleId: string, expectedRevision: string, resolution: ExternalFileResolutionDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies whether a valid text file belongs to the future Markdown editor.
 */
export type TextFileModeDto = "sourceReadOnly" | "markdown";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the lossless text encoding returned by Files.
 */
export type TextEncodingDto = "utf8";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes logical line-ending bytes without modifying them.
 */
export type LineEndingDto = "none" | "lf" | "crlf" | "mixed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one bounded, lossless UTF-8 source snapshot.
 */
export type TextFileDto = { text: string, byteSize: bigint, lineCount: number, mimeType: string, syntaxHint: string | null, encoding: TextEncodingDto, hasUtf8Bom: boolean, lineEnding: LineEndingDto, mode: TextFileModeDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies viewer content without exposing binary bytes.
 */
export type FileContentDto = { "kind": "text", file: TextFileDto, } | { "kind": "binary", byteSize: bigint, mimeType: string, } | { "kind": "tooLarge", byteSize: bigint, limitBytes: bigint, mimeType: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one observed disk version with an opaque fingerprint token.
 */
export type FileDiskVersionDto = { diskRevision: string, observedAtMs: bigint, modifiedAtMs: bigint | null, byteSize: bigint, mimeType: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the current authoritative runtime state of a file handle.
 */
export type FileHandleStateDto = { "kind": "ready", content: FileContentDto, disk: FileDiskVersionDto, } | { "kind": "externalConflict", local: TextFileDto, external: FileDiskVersionDto, } | { "kind": "missing", lastDisk: FileDiskVersionDto | null, local: TextFileDto | null, } | { "kind": "unreadable", lastDisk: FileDiskVersionDto | null, local: TextFileDto | null, } | { "kind": "projectRootChanged" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports whether a handle receives native hints or targeted polling.
 */
export type FileWatchModeDto = "native" | "pollingFallback";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one bounded process-local file handle snapshot.
 */
export type FileHandleDto = { id: string, projectId: string, sessionId: string, tabId: string, paneId: string, name: string, relativePath: string, revision: string, watchMode: FileWatchModeDto, isDirty: boolean, dirtySinceMs: bigint | null, editCount: number, state: FileHandleStateDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports a recoverable post-attach warning.
 */
export type OpenFileWarningDto = "recentFileNotRecorded";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns the attached handle and any bounded post-attach warning.
 */
export type OpenFileResultDto = { file: FileHandleDto, warnings: Array<OpenFileWarningDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies current availability of one durable recent path.
 */
export type RecentFileAvailabilityDto = "available" | "missing" | "notVisible" | "linkDenied" | "projectUnavailable" | "unreadable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns one recent file enriched with current runtime facts.
 */
export type RecentFileDto = { projectId: string, name: string, parentPath: string, relativePath: string, openedAtMs: bigint, availability: RecentFileAvailabilityDto, isOpen: boolean, hasUnsavedChanges: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the visible reason a handle revision changed.
 */
export type FileHandleChangeKindDto = "reloaded" | "conflictDetected" | "missing" | "unreadable" | "projectRootChanged" | "watchModeChanged";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invalidates one handle without sending source content through an event.
 */
export type FileHandleChangedEventDto = { fileHandleId: string, revision: string, change: FileHandleChangeKindDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invalidates the recent list of one project.
 */
export type RecentFilesChangedEventDto = { projectId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes Files failures without exposing native paths or raw errors.
 */
export type FilesError = { "code": "windowNotAllowed" } | { "code": "invalidProjectId" } | { "code": "projectNotFound", project_id: string, } | { "code": "projectUnavailable", project_id: string, } | { "code": "projectRemovalInProgress", project_id: string, } | { "code": "projectAccessFailed" } | { "code": "invalidRelativePath" } | { "code": "invalidSearch" } | { "code": "invalidCursor" } | { "code": "entryNotFound", relative_path: string, } | { "code": "entryNotVisible", relative_path: string, } | { "code": "notDirectory", relative_path: string, } | { "code": "notRegularFile", relative_path: string, } | { "code": "linkTraversalDenied", relative_path: string, } | { "code": "traversalLimitExceeded" } | { "code": "fileSystemReadFailed" } | { "code": "invalidSessionTarget" } | { "code": "paneNotEmpty", pane_id: string, } | { "code": "sessionAttachFailed" } | { "code": "invalidFileHandleId" } | { "code": "fileHandleNotFound", file_handle_id: string, } | { "code": "revisionConflict", current_revision: string, } | { "code": "noExternalConflict" } | { "code": "fileChangedAgain", current_revision: string, } | { "code": "unsavedChangesWouldBeLost" } | { "code": "fileChangedDuringRead" } | { "code": "fileReadFailed" } | { "code": "fileMemoryLimitReached" } | { "code": "projectRootChanged", project_id: string, } | { "code": "revealFailed" } | { "code": "invalidLimit" } | { "code": "recentFilesFailed" } | { "code": "clockFailed" } | { "code": "openExternalFailed" };
