// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests one page of visible direct children.
 */
export type ListFileChildrenRequestDto = { projectId: string, directory: string, cursor: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests a recursive visible-entry basename search.
 */
export type SearchFileTreeRequestDto = { projectId: string, query: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one registered-project entry.
 */
export type FileEntryRequestDto = { projectId: string, relativePath: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a tree entry without following links.
 */
export type FileTreeEntryKindDto = "directory" | "file" | "symbolicLink" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one lossless project-relative filesystem entry.
 */
export type FileTreeEntryDto = { name: string, relativePath: string, kind: FileTreeEntryKindDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a recoverable traversal issue.
 */
export type FileTreeWarningReasonDto = "unreadableEntry" | "invalidIgnoreRule" | "unsupportedName";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports one recoverable issue without leaking an absolute path.
 */
export type FileTreeWarningDto = { relativeDirectory: string, reason: FileTreeWarningReasonDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns a stable page of direct children.
 */
export type FileTreePageDto = { projectId: string, directory: string, entries: Array<FileTreeEntryDto>, nextCursor: string | null, warningCount: number, warningsTruncated: boolean, warnings: Array<FileTreeWarningDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains why a recursive search returned only a deterministic prefix.
 */
export type FileSearchTruncatedReasonDto = "resultLimit" | "scanLimit" | "depthLimit";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns flat matches from one fresh project scan.
 */
export type FileTreeSearchDto = { projectId: string, query: string, matches: Array<FileTreeEntryDto>, truncatedReason: FileSearchTruncatedReasonDto | null, warningCount: number, warningsTruncated: boolean, warnings: Array<FileTreeWarningDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns copyable lexical paths for one freshly validated entry.
 */
export type FileEntryPathsDto = { relativePath: string, absolutePath: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes Files failures without exposing native paths or raw errors.
 */
export type FilesError = { "code": "windowNotAllowed" } | { "code": "invalidProjectId" } | { "code": "projectNotFound", project_id: string, } | { "code": "projectUnavailable", project_id: string, } | { "code": "projectRemovalInProgress", project_id: string, } | { "code": "projectAccessFailed" } | { "code": "invalidRelativePath" } | { "code": "invalidSearch" } | { "code": "invalidCursor" } | { "code": "entryNotFound", relative_path: string, } | { "code": "entryNotVisible", relative_path: string, } | { "code": "notDirectory", relative_path: string, } | { "code": "linkTraversalDenied", relative_path: string, } | { "code": "traversalLimitExceeded" } | { "code": "fileSystemReadFailed" } | { "code": "projectRootChanged", project_id: string, } | { "code": "revealFailed" };
