// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains why a persisted project root is currently unusable.
 */
export type ProjectUnavailableReasonDto = "missing" | "notDirectory" | "accessDenied" | "io";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports whether a project root is usable right now.
 */
export type ProjectAvailabilityDto = { "status": "available" } | { "status": "unavailable", "reason": ProjectUnavailableReasonDto };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one registered project and its freshly measured availability.
 */
export type ProjectDto = { id: string, displayName: string, rootPath: string, isPinned: boolean, addedAtMs: number, lastOpenedAtMs: number, availability: ProjectAvailabilityDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports the outcome of a native folder selection flow.
 */
export type ProjectFolderSelectionDto = { "outcome": "cancelled" } | { "outcome": "selected", project: ProjectDto, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes a plain folder, worktree, and bare repository.
 */
export type GitRepositoryKindDto = "notRepository" | "worktree" | "bare";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the branch, unborn branch, or detached commit at HEAD.
 */
export type GitHeadDto = { "kind": "branch", name: string, } | { "kind": "unborn", name: string, } | { "kind": "detached", shortOid: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies the highest-priority visible change for one path.
 */
export type GitFileChangeKindDto = "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChanged" | "untracked" | "conflicted";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes one deduplicated path in a detailed Git snapshot.
 */
export type GitFileChangeDto = { path: string, previousPath: string | null, change: GitFileChangeKindDto, isDirectory: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarizes the repository and visible changes for one project.
 */
export type ProjectGitSummaryDto = { projectId: string, repositoryKind: GitRepositoryKindDto, head: GitHeadDto | null, changedCount: number, untrackedCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returns a Git summary together with its stable, project-relative entries.
 */
export type ProjectGitStatusDto = { summary: ProjectGitSummaryDto, changes: Array<GitFileChangeDto>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplies the facts a remove-confirmation dialog must show.
 */
export type RemoveProjectImpactDto = { projectId: string, displayName: string, rootPath: string, sessionCount: number, runningProcessCount: number, unsavedFileCount: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the project whose metadata was removed.
 */
export type RemoveProjectResultDto = { projectId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies the committed mutation that produced a change event.
 */
export type ProjectChangeKindDto = "added" | "updated" | "removed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries the invalidation key emitted after a committed project mutation.
 */
export type ProjectChangedEventDto = { change: ProjectChangeKindDto, projectId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains why a selected folder cannot be registered as a project root.
 */
export type InvalidProjectFolderReasonDto = "notAbsolute" | "missing" | "notDirectory" | "fileSystemRoot" | "notUtf8" | "accessDenied" | "cannotCanonicalize";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes Projects failures without exposing SQL, bind values, or system paths.
 */
export type ProjectsError = { "code": "unauthorizedWindow" } | { "code": "invalidProjectId" } | { "code": "projectNotFound", project_id: string, } | { "code": "invalidSearch" } | { "code": "invalidDisplayName" } | { "code": "folderPickerFailed" } | { "code": "invalidProjectFolder", reason: InvalidProjectFolderReasonDto, } | { "code": "projectAlreadyExists", project_id: string, } | { "code": "projectUnavailable", reason: ProjectUnavailableReasonDto, } | { "code": "removalInProgress", project_id: string, } | { "code": "confirmationRequired", impact: RemoveProjectImpactDto, } | { "code": "runtimeInspectionFailed" } | { "code": "runtimeCleanupFailed" } | { "code": "gitInspectionFailed", project_id: string, } | { "code": "openFolderFailed" } | { "code": "clockFailed" } | { "code": "persistenceFailed" };
